from django.shortcuts import render
from API import models
from collections import OrderedDict

# Create your views here.
def home(request):
    params = {
    	'attributes': [
    		{'short': 'bod', 'full': 'Body', 'type': 'attribute'}, 
    		{'short': 'agi', 'full': 'Agility', 'type': 'attribute'},
    		{'short': 'rea', 'full': 'Reaction', 'type': 'attribute'}, 
    		{'short': 'str', 'full': 'Strength', 'type': 'attribute'}, 
    		{'short': 'cha', 'full': 'Charisma', 'type': 'attribute'}, 
    		{'short': 'int', 'full': 'Intuition', 'type': 'attribute'}, 
    		{'short': 'log', 'full': 'Logic', 'type': 'attribute'}, 
    		{'short': 'wil', 'full': 'Willpower', 'type': 'attribute'}, 
    		{'short': 'edg', 'full': 'Edge', 'type': 'special'}, 
    		{'short': 'mag', 'full': 'Magic', 'type': 'special'}, 
    		{'short': 'res', 'full': 'Resonance', 'type': 'special'}
    	],
        'positive_qualities': models.PositiveQualities.objects.all(),
        'negative_qualities': models.NegativeQualities.objects.all(),
        'skill_groups': [
            {'name': 'Acting', 'skills': ('Con', 'Impersonation', 'Performance')},
            {'name': 'Athletics', 'skills': ('Gymnastics', 'Running', 'Swimming',)},
            {'name': 'Biotech', 'skills': ('Cybertechnology', 'First Aid', 'Medicine',)},
            {'name': 'Close Combat', 'skills': ('Blades', 'Clubs', 'Unarmed Combat',)},
            {'name': 'Conjouring', 'skills': ('Banishing', 'Binding', 'Summoning',)},
            {'name': 'Cracking', 'skills': ('Cybercombat', 'Electronic Warfare', 'Hacking',)},
            {'name': 'Electronics', 'skills': ('Computer', 'Hardware', 'Software',)},
            {'name': 'Enchanting', 'skills': ('Alchemy', 'Artificing', 'Disenchanting',)},
            {'name': 'Engineering', 'skills': ('Aeronautics Mechanic', 'Automotive Mechanic', 'Industrial Mechanic', 'Nautical Mechanic',)},
            {'name': 'Firearms', 'skills': ('Automatics', 'Longarms', 'Pistols',)},
            {'name': 'Influence', 'skills': ('Etiquette', 'Leadership', 'Negotiation',)},
            {'name': 'Outdoors', 'skills': ('Navigation', 'Survival', 'Tracking',)},
            {'name': 'Sorcery', 'skills': ('Counterspelling', 'Ritual Spellcasting', 'Spellcasting',)},
            {'name': 'Stealth', 'skills': ('Disguise', 'Palming', 'Sneaking',)},
            {'name': 'Tasking', 'skills': ('Compiling', 'Decompiling', 'Registering',)}
        ],
        'skills': [
            {'name': 'Aeronautics Mechanic', 'id': 'aeronauticsmechanic'},
            {'name': 'Alchemy', 'id': 'alchemy'},
            {'name': 'Artificing', 'id': 'artificing'},
            {'name': 'Automatics', 'id': 'automatics'},
            {'name': 'Automotive Mechanic', 'id': 'automotivemechanic'},
            {'name': 'Banishing', 'id': 'banishing'},
            {'name': 'Binding', 'id': 'binding'},
            {'name': 'Blades', 'id': 'blades'},
            {'name': 'Clubs', 'id': 'clubs'},
            {'name': 'Compiling', 'id': 'compiling'},
            {'name': 'Computer', 'id': 'computer'},
            {'name': 'Con', 'id': 'con'},
            {'name': 'Counterspelling', 'id': 'counterspelling'},
            {'name': 'Cybercombat', 'id': 'cybercombat'},
            {'name': 'Cybertechnology', 'id': 'cybertechnology'},
            {'name': 'Decompiling', 'id': 'decompiling'},
            {'name': 'Disenchanting', 'id': 'disenchanting'},
            {'name': 'Disguise', 'id': 'disguise'},
            {'name': 'Electronic Warfare', 'id': 'electronicwarfare'},
            {'name': 'Etiquette', 'id': 'etiquette'},
            {'name': 'First Aid', 'id': 'firstaid'},
            {'name': 'Gymnastics', 'id': 'gymnastics'},
            {'name': 'Hacking', 'id': 'hacking'},
            {'name': 'Hardware', 'id': 'hardware'},
            {'name': 'Impersonation', 'id': 'impersonation'},
            {'name': 'Industrial Mechanic', 'id': 'industrialmechanic'},
            {'name': 'Leadership', 'id': 'leadership'},
            {'name': 'Longarms', 'id': 'longarms'},
            {'name': 'Medicine', 'id': 'medicine'},
            {'name': 'Nautical Mechanic', 'id': 'nauticalmechanic'},
            {'name': 'Navigation', 'id': 'navigation'},
            {'name': 'Negotiation', 'id': 'negotiation'},
            {'name': 'Palming', 'id': 'palming'},
            {'name': 'Performance', 'id': 'performance'},
            {'name': 'Pistols', 'id': 'pistols'},
            {'name': 'Registering', 'id': 'registering'},
            {'name': 'Ritual Spellcasting', 'id': 'ritualspellcasting'},
            {'name': 'Running', 'id': 'running'},
            {'name': 'Sneaking', 'id': 'sneaking'},
            {'name': 'Software', 'id': 'software'},
            {'name': 'Spellcasting', 'id': 'spellcasting'},
            {'name': 'Summoning', 'id': 'summoning'},
            {'name': 'Survival', 'id': 'survival'},
            {'name': 'Swimming', 'id': 'swimming'},
            {'name': 'Tracking', 'id': 'tracking'},
            {'name': 'Unarmed Combat', 'id': 'unarmedcombat'},
        ]
    }

    return render(request, 'main.html', params)